import '../../supabase-client.js';
import '../../supabase-auth.js';

let selectedFile = null;
        let uploading = false;
        let selectedAuctionDuration = null;
        let latestAIValuation = null;
        let latestAIValuationFormKey = '';
        let aiValuationRequestId = 0;
        let aiValuationController = null;
        let aiValuationAttemptCount = 0;
        let authorizationInProgress = false;
        let authorizedWalletAddress = '';
        let publishNavigationLocked = false;
        let currentPublishStage = 'idle';

        const AI_ANALYSIS_TIMEOUT_MS = 20000;
        const AI_PREVIEW_MAX_DATA_URL_LENGTH = 1800000;
        const AI_TOTAL_ATTEMPT_LIMIT = 3;
        const MAX_UPLOAD_BYTES = 100 * 1024 * 1024;
        const BASE_SEPOLIA_CHAIN_ID = 84532;
        const SUPPORTED_FILE_TYPES = new Set([
            'image/jpeg', 'image/png', 'image/gif', 'image/webp',
            'video/mp4', 'video/webm', 'video/quicktime',
            'audio/mpeg', 'audio/mp3', 'audio/wav', 'audio/x-wav',
            'audio/ogg', 'audio/aac', 'audio/mp4'
        ]);

        function getTransactionErrorMessage(error, fallback) {
            return window.ArtSoulTransactionErrors?.message?.(error, fallback) ||
                error?.shortMessage ||
                error?.reason ||
                error?.message ||
                fallback;
        }

        function setTransactionButtonProcessing(button, label = 'Processing...') {
            button.disabled = true;
            button.setAttribute('aria-busy', 'true');
            button.innerHTML = `<span class="inline-flex items-center justify-center gap-2"><span class="inline-block h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" aria-hidden="true"></span>${label}</span>`;
        }

        function restoreTransactionButton(button, originalMarkup) {
            button.removeAttribute('aria-busy');
            button.innerHTML = originalMarkup;
            updatePublishReadiness();
        }

        const PLACEHOLDER_TITLES = new Set([
            'test',
            'testing',
            'screenshot',
            'screen shot',
            'image',
            'img',
            'photo',
            'picture',
            'untitled',
            'new artwork',
            'artwork',
            'video',
            'audio'
        ]);

        function normalizeArtworkTitle(value) {
            return (value || '').trim().replace(/\s+/g, ' ');
        }

        function simplifyArtworkTitle(value) {
            return normalizeArtworkTitle(value)
                .toLowerCase()
                .replace(/\.[a-z0-9]{2,5}$/i, '')
                .replace(/[_-]+/g, ' ')
                .replace(/\s+/g, ' ')
                .trim();
        }

        function isPlaceholderArtworkTitle(value) {
            const simplified = simplifyArtworkTitle(value);
            if (PLACEHOLDER_TITLES.has(simplified)) return true;
            return /^(screenshot|screen shot|img|image|photo|picture|untitled)\b/i.test(simplified);
        }

        function validateArtworkDetails({ title, description, price }) {
            const cleanTitle = normalizeArtworkTitle(title);
            const cleanDescription = (description || '').trim().replace(/\s+/g, ' ');

            if (Array.from(cleanTitle).length < 3) {
                return 'Use a clear artwork title with at least 3 characters.';
            }

            if (isPlaceholderArtworkTitle(cleanTitle)) {
                return 'Use a clear artwork title, not a placeholder like test, screenshot, image, or untitled.';
            }

            if (!cleanDescription || Array.from(cleanDescription).length < 12) {
                return 'Add a short meaningful description with the story, medium, or collector context.';
            }

            if (!price || parseFloat(price) <= 0) {
                return 'Price must be greater than 0.';
            }

            return '';
        }

        function createUploadError(code, message) {
            const error = new Error(message);
            error.code = code;
            return error;
        }

        function isAutoGeneratedFilename(fileName) {
            const baseName = String(fileName || '')
                .normalize('NFKC')
                .replace(/\.[^.]+$/, '')
                .trim();
            const simplified = baseName.toLowerCase().replace(/[\s_-]+/g, '_');
            const compact = simplified.replace(/[^a-z0-9а-яё]/gi, '');

            if (/^(screenshot|screen_?shot|скриншот|снимок_?экрана)(_|$)/iu.test(simplified)) return true;
            if (/^(img|dsc|dcim|pxl|mvimg|vid)_?\d{3,}$/i.test(simplified)) return true;
            if (/^photo_?\d{4}[-_]\d{2}[-_]\d{2}(?:[-_]\d{2}){2,3}$/i.test(simplified)) return true;
            if (/^file_?[0-9a-f]{16,}$/i.test(simplified)) return true;
            if (/^[0-9a-f]{20,}$/i.test(compact)) return true;
            if (/^\d{10,}$/.test(compact)) return true;
            return false;
        }

        function validateArtworkFile(file) {
            if (!file) {
                return { code: 'FILE_REQUIRED', message: 'Select an artwork file before continuing.' };
            }
            if (isAutoGeneratedFilename(file.name)) {
                return {
                    code: 'INVALID_FILENAME',
                    message: 'This file name looks auto-generated. Please rename the file to a meaningful title (for example: my-artwork.png) and try again.'
                };
            }
            if (!SUPPORTED_FILE_TYPES.has(String(file.type || '').toLowerCase())) {
                return {
                    code: 'UNSUPPORTED_FILE_TYPE',
                    message: 'This file type is not supported. Upload a JPG, PNG, WebP, GIF, MP4, WebM, MOV, MP3, WAV, OGG, AAC, or M4A file.'
                };
            }
            if (!Number.isFinite(file.size) || file.size <= 0) {
                return { code: 'EMPTY_FILE', message: 'This file is empty. Choose a valid artwork file and try again.' };
            }
            if (file.size > MAX_UPLOAD_BYTES) {
                return { code: 'FILE_TOO_LARGE', message: 'This file is too large. The maximum size is 100 MB.' };
            }
            return null;
        }

        function describeAIValuationError(error) {
            const status = Number(error?.status || error?.statusCode || 0);
            const message = String(error?.message || '').toLowerCase();
            if (error?.name === 'AbortError') {
                return 'AI value guidance took too long to respond. Please try again.';
            }
            if (status === 429 || message.includes('high demand') || message.includes('rate limit') || message.includes('limit reached')) {
                return 'AI value guidance is temporarily busy because of high demand. Please try again shortly.';
            }
            if (message.includes('wallet') || message.includes('creator')) {
                return 'Connect your wallet to request AI value guidance.';
            }
            return 'AI value guidance is temporarily unavailable. Please try again.';
        }

        function describePublishError(error) {
            const code = error?.code || '';
            if (code === 'SERVICE_ROLE_KEY_NOT_SERVICE_ROLE') {
                return 'Artwork storage is temporarily unavailable. Please try again later.';
            }
            if (code === 'MISSING_SERVICE_ROLE_KEY') {
                return 'Artwork storage is temporarily unavailable. Please try again later.';
            }
            if (code === 'STORAGE_SIGNED_UPLOAD_RLS_DENIED') {
                return 'Artwork storage could not authorize this upload. Please reconnect your wallet and try again.';
            }
            if (code === 'STORAGE_BUCKET_NOT_FOUND') {
                return 'Artwork storage is temporarily unavailable. Please try again later.';
            }
            if (code === 'INVALID_UPLOAD_PAYLOAD') {
                const reason = String(error?.reason || '').toUpperCase();
                if (reason.includes('FILENAME')) return 'This file name looks auto-generated. Please rename the file to a meaningful title (for example: my-artwork.png) and try again.';
                if (reason.includes('EMPTY')) return 'This file is empty. Choose a valid artwork file and try again.';
                if (reason.includes('SIZE')) return 'This file is too large. The maximum size is 100 MB.';
                if (reason.includes('TYPE')) return 'This file type is not supported. Choose a supported image, video, or audio file.';
                return 'The selected file is not valid. Check its type and size, then try again.';
            }
            const stageMessages = {
                fingerprint: 'The selected file could not be read. Choose the file again and retry.',
                media_upload: 'The artwork file could not be stored. Check your connection and try again.',
                metadata_upload: 'The artwork details could not be stored. Please try again.',
                wallet_init: 'The connected wallet could not be prepared for publishing. Reconnect it and try again.',
                register: 'The artwork could not be registered on Base Sepolia. Please try again.',
                auction: 'The artwork was registered, but its auction could not be created. Retry the auction from your profile.'
            };
            return stageMessages[currentPublishStage] || 'The publish flow could not be completed. Please try again.';
        }

        function mapPublishError(error) {
            const code = String(error?.code || '').toUpperCase();
            const message = String(error?.shortMessage || error?.reason || error?.message || '');
            const lower = message.toLowerCase();

            if (code === 'ACTION_REJECTED' || code === '4001' || lower.includes('user rejected') || lower.includes('user denied')) {
                return { code: 'USER_REJECTED', message: 'The transaction was rejected in your wallet. No artwork was published.' };
            }
            if (lower.includes('nonce too low')) {
                return { code: 'NONCE_TOO_LOW', message: 'Your wallet has a pending transaction. Wait for it to finish, then try again.' };
            }
            if (lower.includes('insufficient funds') || lower.includes('insufficient gas') || lower.includes('not enough funds')) {
                return { code: 'INSUFFICIENT_FUNDS', message: 'Insufficient ETH on Base Sepolia to publish this artwork. Top up your wallet and try again.' };
            }
            if (code === 'CALL_EXCEPTION' || lower.includes('reverted') || lower.includes('execution reverted')) {
                return {
                    code: 'TRANSACTION_REVERTED',
                    message: currentPublishStage === 'auction'
                        ? 'The artwork was registered, but the auction transaction failed on Base Sepolia. Retry the auction from your profile.'
                        : 'The artwork registration transaction failed on Base Sepolia. No artwork was published.'
                };
            }
            if (lower.includes('no wallet provider') || (lower.includes('wallet provider') && lower.includes('not available'))) {
                return { code: 'WALLET_NOT_CONNECTED', message: 'Connect your wallet before publishing this artwork.' };
            }
            if (lower.includes('network was changed') || code === 'NETWORK_ERROR') {
                return { code: 'NETWORK_CHANGED', message: 'The wallet network changed during publishing. Switch back to Base Sepolia and try again.' };
            }
            if (lower.includes('metadata upload')) {
                return { code: 'METADATA_UPLOAD_FAILED', message: 'The artwork details could not be stored. Please try again.' };
            }
            if (lower.includes('storage upload') || lower.includes('upload authorization')) {
                return { code: 'MEDIA_UPLOAD_FAILED', message: 'The artwork file could not be stored. Check your connection and try again.' };
            }
            if (lower.includes('confirmed artwork id') || lower.includes('register transaction did not return')) {
                return { code: 'REGISTRATION_INCOMPLETE', message: 'The wallet did not return a complete artwork registration confirmation. Check your profile before retrying.' };
            }
            if (lower.includes('unsupported network') || lower.includes('wrong network')) {
                return { code: 'UNSUPPORTED_NETWORK', message: 'This artwork must be published on Base Sepolia. Switch networks and try again.' };
            }
            if (lower.includes('duplicate artwork')) {
                return { code: 'DUPLICATE_ARTWORK', message: 'This file has already been published.' };
            }

            const directMessages = {
                FILE_REQUIRED: 'Select an artwork file before continuing.',
                INVALID_FILENAME: 'This file name looks auto-generated. Please rename the file to a meaningful title (for example: my-artwork.png) and try again.',
                FILE_TOO_LARGE: 'This file is too large. The maximum size is 100 MB.',
                UNSUPPORTED_FILE_TYPE: 'This file type is not supported. Choose a supported image, video, or audio file.',
                WALLET_NOT_CONNECTED: 'Connect your wallet before publishing this artwork.',
                AUTHORIZATION_REQUIRED: 'Authorize this upload with your wallet signature before publishing.',
                AI_UNAVAILABLE: 'AI value guidance is not ready. Request an estimate before publishing.'
            };
            if (directMessages[code]) return { code, message: directMessages[code] };

            return { code: code || 'PUBLISH_FAILED', message: describePublishError(error) };
        }

        const PENDING_ARTWORKS_KEY = 'artsoul_pending_indexer_artworks';

        function readPendingArtworks() {
            try {
                const parsed = JSON.parse(localStorage.getItem(PENDING_ARTWORKS_KEY) || '[]');
                return Array.isArray(parsed) ? parsed : [];
            } catch {
                return [];
            }
        }

        function savePendingArtwork(record) {
            if (!record?.temp_id) return record;
            const now = new Date().toISOString();
            const nextRecord = {
                ...record,
                source: 'pending_indexer',
                status: 'pending_indexer',
                updated_at: now
            };
            const existing = readPendingArtworks()
                .filter(item => item?.temp_id !== nextRecord.temp_id)
                .filter(item => item?.register_tx_hash !== nextRecord.register_tx_hash || !nextRecord.register_tx_hash);
            localStorage.setItem(PENDING_ARTWORKS_KEY, JSON.stringify([nextRecord, ...existing].slice(0, 20)));
            return nextRecord;
        }

        function removePendingArtwork(tempId) {
            if (!tempId) return;
            const kept = readPendingArtworks().filter((item) => item?.temp_id !== tempId);
            localStorage.setItem(PENDING_ARTWORKS_KEY, JSON.stringify(kept));
        }

        function hasRegisterTx(record) {
            return Boolean(String(record?.register_tx_hash || '').trim());
        }

        function isBadPendingArtwork(record) {
            if (hasRegisterTx(record)) return false;
            const state = [
                record?.status,
                record?.stage,
                record?.error_code,
                record?.error_message
            ].join(' ').toLowerCase();
            return !hasRegisterTx(record) ||
                state.includes('fail') ||
                state.includes('error') ||
                state.includes('reject') ||
                state.includes('revert') ||
                state.includes('nonce');
        }

        function cleanupBadPendingCards() {
            const current = readPendingArtworks();
            const kept = current.filter(record => !isBadPendingArtwork(record));
            localStorage.setItem(PENDING_ARTWORKS_KEY, JSON.stringify(kept));
            const result = { removed: current.length - kept.length, kept: kept.length };
            console.info('ArtSoul pending-card cleanup complete:', result);
            return result;
        }

        window.ArtSoulCleanupBadPendingCards = cleanupBadPendingCards;

        function createPendingArtworkDraft({ walletAddress, title, description, price, fileHash, fileUpload }) {
            const now = new Date().toISOString();
            return {
                temp_id: crypto.randomUUID?.() || `pending-${Date.now()}`,
                id: `pending:${Date.now()}`,
                chain_id: window.ArtSoulContracts?.currentNetwork?.chainId || 84532,
                network: window.ArtSoulContracts?.currentNetwork?.key || 'baseSepolia',
                wallet_address: walletAddress.toLowerCase(),
                creator: walletAddress,
                creator_id: walletAddress,
                title,
                description,
                creator_value: price,
                file_hash: fileHash,
                file_url: fileUpload.url,
                media_url: fileUpload.url,
                file_type: selectedFile?.type?.split('/')[0] || 'image',
                media_type: selectedFile?.type || '',
                storage_path: fileUpload.path || fileUpload.storagePath || '',
                upload_hash: fileUpload.ipfsHash || '',
                stage: 'media_uploaded',
                created_at: now,
                updated_at: now
            };
        }

        function selectAuctionDuration(hours) {
            selectedAuctionDuration = [24, 36, 48].includes(Number(hours)) ? Number(hours) : null;
            document.querySelectorAll('.duration-option').forEach(button => {
                button.setAttribute('aria-pressed', String(Number(button.dataset.duration) === selectedAuctionDuration));
            });
            document.getElementById('auctionDurationError').style.display = 'none';
            updatePublishReadiness();
        }

        function clearOriginalWorkError() {
            document.getElementById('originalWorkError').style.display = 'none';
            updatePublishReadiness();
        }

        function getUploadFormValues() {
            return {
                title: normalizeArtworkTitle(document.getElementById('artTitle')?.value),
                description: document.getElementById('artDescription')?.value.trim() || '',
                price: document.getElementById('artPrice')?.value || '',
                duration: selectedAuctionDuration,
                originalConfirmed: Boolean(document.getElementById('originalWorkConfirm')?.checked)
            };
        }

        function getAIValuationFormKey() {
            const values = getUploadFormValues();
            return JSON.stringify({
                file: selectedFile ? [selectedFile.name, selectedFile.size, selectedFile.lastModified] : null,
                title: values.title,
                description: values.description,
                price: values.price,
                duration: values.duration,
                originalConfirmed: values.originalConfirmed
            });
        }

        function getFormCompletionError() {
            const fileError = validateArtworkFile(selectedFile);
            if (fileError) return fileError.message;

            const values = getUploadFormValues();
            const detailsError = validateArtworkDetails(values);
            if (detailsError) return detailsError;
            if (!values.duration) return 'Choose a 24, 36, or 48 hour auction duration.';
            if (!values.originalConfirmed) return 'Confirm that this is your original work.';
            return '';
        }

        function setFileValidationError(message = '') {
            const error = document.getElementById('fileValidationError');
            if (!error) return;
            error.textContent = message;
            error.style.display = message ? 'block' : 'none';
        }

        function updatePrePublishAction() {
            const action = document.getElementById('prePublishAction');
            if (!action) return;
            const formError = getFormCompletionError();
            const currentKey = getAIValuationFormKey();
            const estimateCurrent = Boolean(latestAIValuation && latestAIValuationFormKey === currentKey);
            const canStart = !formError && !estimateCurrent && !aiValuationController && !authorizationInProgress && aiValuationAttemptCount === 0;
            action.style.display = canStart ? 'inline-flex' : 'none';
            action.disabled = !canStart;
            action.textContent = window.getCurrentWalletAddress?.()
                ? 'Authorize and analyze'
                : 'Connect, authorize, and analyze';
        }

        function updatePublishReadiness(message = '') {
            const button = document.getElementById('publishBtn');
            const hint = document.getElementById('publishReadinessHint');
            if (!button || !hint) return false;

            const formError = getFormCompletionError();
            const currentKey = getAIValuationFormKey();
            const walletAddress = String(window.getCurrentWalletAddress?.() || '').toLowerCase();
            const estimateCurrent = Boolean(latestAIValuation && latestAIValuationFormKey === currentKey);
            const authorizationCurrent = Boolean(walletAddress && authorizedWalletAddress === walletAddress);
            const ready = !uploading && !formError && authorizationCurrent && estimateCurrent && !aiValuationController && !authorizationInProgress;

            button.disabled = !ready;
            if (message) hint.textContent = message;
            else if (formError) hint.textContent = formError;
            else if (authorizationInProgress) hint.textContent = 'Waiting for wallet authorization.';
            else if (!authorizationCurrent) hint.textContent = 'Authorize the upload with your wallet, then request AI value guidance.';
            else if (aiValuationController) hint.textContent = 'Waiting for AI value guidance.';
            else if (!estimateCurrent) hint.textContent = 'AI value guidance is required before publishing.';
            else hint.textContent = 'Ready to publish.';

            updatePrePublishAction();
            return ready;
        }

        async function ensureUploadAuthorization() {
            let walletAddress = window.getCurrentWalletAddress?.();
            if (!walletAddress) {
                walletAddress = await window.safeConnectWallet?.();
            }
            if (!walletAddress) {
                throw createUploadError('WALLET_NOT_CONNECTED', 'Connect your wallet to continue.');
            }

            const chainId = Number(window.getCurrentChainId?.() || window.ArtSoulContracts?.currentNetwork?.chainId || 0);
            if (chainId && chainId !== BASE_SEPOLIA_CHAIN_ID) {
                throw createUploadError('UNSUPPORTED_NETWORK', 'This artwork must be published on Base Sepolia. Switch networks and try again.');
            }

            const alreadyAuthenticated = await (
                window.SupabaseAuth?.isAuthenticatedForWallet?.(walletAddress) ||
                window.SupabaseAuth?.isAuthenticated?.(walletAddress)
            );
            if (!alreadyAuthenticated) {
                const authenticated = await window.ensureAuthenticated?.();
                if (!authenticated) {
                    throw createUploadError(
                        'AUTHORIZATION_REQUIRED',
                        'Wallet authorization was not completed. Tap the authorization button again when your wallet is ready.'
                    );
                }
            }

            authorizedWalletAddress = walletAddress.toLowerCase();
            return walletAddress;
        }

        async function beginPrePublishFlow() {
            if (authorizationInProgress || aiValuationController) return;
            const formError = getFormCompletionError();
            if (formError) {
                updatePublishReadiness(formError);
                return;
            }

            authorizationInProgress = true;
            updatePublishReadiness('Waiting for wallet authorization.');
            setAIValuationState('unavailable', { message: 'Confirm the gas-free wallet authorization to continue.' });

            try {
                await ensureUploadAuthorization();
                await requestAIValuation(selectedFile);
            } catch (error) {
                const mapped = mapPublishError(error);
                setAIValuationState('unavailable', { message: mapped.message });
                updatePublishReadiness(mapped.message);
            } finally {
                authorizationInProgress = false;
                updateAIValuationRetryState();
                updatePublishReadiness();
            }
        }

        function formatEthEstimate(value) {
            const numeric = Number(value);
            if (!Number.isFinite(numeric)) return '0';
            return numeric.toLocaleString(undefined, { maximumFractionDigits: 6 });
        }

        function updateAIValuationRetryState() {
            const retry = document.getElementById('aiValuationRetry');
            const note = document.getElementById('aiValuationRetryNote');
            const attemptsLeft = Math.max(0, AI_TOTAL_ATTEMPT_LIMIT - aiValuationAttemptCount);
            const limitReached = aiValuationAttemptCount >= AI_TOTAL_ATTEMPT_LIMIT;
            const canRetry = Boolean(
                selectedFile &&
                aiValuationAttemptCount > 0 &&
                attemptsLeft > 0 &&
                !aiValuationController &&
                !authorizationInProgress &&
                !getFormCompletionError()
            );

            retry.disabled = !canRetry;
            retry.style.display = canRetry ? 'inline-flex' : 'none';
            retry.textContent = `Retry (${attemptsLeft} ${attemptsLeft === 1 ? 'attempt' : 'attempts'} left)`;
            note.style.display = limitReached ? 'block' : 'none';
            note.textContent = 'AI value guidance limit reached for this upload session.';
        }

        function setAIValuationState(state, details = {}) {
            const status = document.getElementById('aiValuationStatus');
            const content = document.getElementById('aiValuationContent');
            const retry = document.getElementById('aiValuationRetry');
            const range = document.getElementById('aiValuationRange');
            const suggestion = document.getElementById('aiValuationSuggestion');
            const rationale = document.getElementById('aiValuationRationale');

            if (state === 'loading') {
                status.textContent = 'Analyzing the artwork...';
                content.style.display = 'none';
                retry.style.display = 'none';
                retry.disabled = true;
                updatePublishReadiness('Waiting for AI value guidance.');
                return;
            }

            if (state === 'ready' && details.valuation) {
                const valuation = details.valuation;
                const attemptsLeft = Math.max(0, AI_TOTAL_ATTEMPT_LIMIT - aiValuationAttemptCount);
                status.textContent = `AI value guidance is ready. Review the estimate below. You have ${attemptsLeft} ${attemptsLeft === 1 ? 'attempt' : 'attempts'} left to run it again.`;
                if (!details.logged) {
                    status.textContent += ' The estimate is ready, but its activity log is temporarily unavailable.';
                }
                range.textContent = `${formatEthEstimate(valuation.estimated_value_min_eth)} - ${formatEthEstimate(valuation.estimated_value_max_eth)} ETH`;
                suggestion.textContent = `Suggested starting price: ${formatEthEstimate(valuation.suggested_start_price_eth)} ETH - ${valuation.confidence || 'medium'} confidence`;
                rationale.textContent = valuation.rationale || '';
                content.style.display = 'block';
                updateAIValuationRetryState();
                updatePublishReadiness();
                return;
            }

            status.textContent = details.message || 'AI value guidance is temporarily unavailable. Please try again.';
            content.style.display = 'none';
            updateAIValuationRetryState();
            updatePublishReadiness();
        }

        async function createAIImagePreview(file) {
            if (!file?.type?.startsWith('image/')) return '';

            const objectUrl = URL.createObjectURL(file);
            try {
                const image = await new Promise((resolve, reject) => {
                    const element = new Image();
                    element.onload = () => resolve(element);
                    element.onerror = reject;
                    element.src = objectUrl;
                });

                let maxDimension = 1024;
                for (let attempt = 0; attempt < 3; attempt += 1) {
                    const scale = Math.min(1, maxDimension / Math.max(image.naturalWidth, image.naturalHeight));
                    const canvas = document.createElement('canvas');
                    canvas.width = Math.max(1, Math.round(image.naturalWidth * scale));
                    canvas.height = Math.max(1, Math.round(image.naturalHeight * scale));
                    canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height);
                    const dataUrl = canvas.toDataURL('image/webp', 0.78);
                    if (dataUrl.length <= AI_PREVIEW_MAX_DATA_URL_LENGTH) return dataUrl;
                    maxDimension = Math.round(maxDimension * 0.7);
                }
            } catch (error) {
                console.warn('[AI Guidance] Could not prepare image preview:', error);
            } finally {
                URL.revokeObjectURL(objectUrl);
            }

            return '';
        }

        function retryAIValuation() {
            if (!selectedFile || aiValuationController) return;
            if (aiValuationAttemptCount >= AI_TOTAL_ATTEMPT_LIMIT) {
                updateAIValuationRetryState();
                return;
            }
            beginPrePublishFlow();
        }

        async function requestAIValuation(file = selectedFile) {
            if (!file) {
                setAIValuationState('unavailable', { message: 'Select an artwork file before requesting AI value guidance.' });
                return;
            }

            const formError = getFormCompletionError();
            if (formError) {
                setAIValuationState('unavailable', { message: formError });
                return;
            }

            if (aiValuationAttemptCount >= AI_TOTAL_ATTEMPT_LIMIT) {
                updateAIValuationRetryState();
                return;
            }

            const requestId = ++aiValuationRequestId;
            const requestFormKey = getAIValuationFormKey();
            const requestValues = getUploadFormValues();
            latestAIValuation = null;
            aiValuationController?.abort();
            const controller = new AbortController();
            aiValuationController = controller;
            const timeout = setTimeout(() => controller.abort(), AI_ANALYSIS_TIMEOUT_MS);
            aiValuationAttemptCount += 1;
            setAIValuationState('loading');

            try {
                const walletAddress = window.getCurrentWalletAddress?.();
                const mediaDataUrl = await createAIImagePreview(file);
                if (requestId !== aiValuationRequestId) return;

                const result = await window.ArtSoulAIValuation.request({
                        title: requestValues.title,
                        description: requestValues.description,
                        creator_value: requestValues.price,
                        media_type: file.type,
                        creator: walletAddress,
                        chain_id: window.getCurrentChainId?.() || 84532,
                        media_data_url: mediaDataUrl || undefined
                    }, { signal: controller.signal });
                if (requestId !== aiValuationRequestId) return;
                if (requestFormKey !== getAIValuationFormKey()) {
                    setAIValuationState('unavailable', {
                        message: 'Artwork details changed during analysis. Request updated AI value guidance.'
                    });
                    return;
                }

                latestAIValuation = result.valuation;
                latestAIValuationFormKey = requestFormKey;
                if (!result.logged) {
                    console.warn('[AI Guidance] Estimate returned but ai_valuations logging was unavailable.');
                }
                setAIValuationState('ready', {
                    valuation: latestAIValuation,
                    logged: result.logged
                });
            } catch (error) {
                if (requestId !== aiValuationRequestId) return;
                const message = describeAIValuationError(error);
                console.warn('[AI Guidance] Analysis unavailable:', error);
                setAIValuationState('unavailable', { message });
            } finally {
                clearTimeout(timeout);
                if (aiValuationController === controller) {
                    aiValuationController = null;
                    updateAIValuationRetryState();
                    updatePublishReadiness();
                }
            }
        }

        function handleFileSelect(event) {
            const file = event.target.files[0];
            if (!file) return;

            const fileError = validateArtworkFile(file);
            if (fileError) {
                selectedFile = null;
                event.target.value = '';
                setFileValidationError(fileError.message);
                document.getElementById('uploadPrompt').style.display = 'block';
                document.getElementById('fileInfo').style.display = 'none';
                setAIValuationState('unavailable', {
                    message: 'Choose a valid artwork file before requesting AI value guidance.'
                });
                updatePublishReadiness(fileError.message);
                alert(fileError.message);
                return;
            }

            selectedFile = file;
            latestAIValuation = null;
            latestAIValuationFormKey = '';
            aiValuationAttemptCount = 0;
            authorizedWalletAddress = '';
            aiValuationController?.abort();
            setFileValidationError('');
            document.getElementById('fileName').textContent = `Selected: ${file.name} (${(file.size / 1024 / 1024).toFixed(2)} MB)`;

            // Hide upload prompt, show file info
            document.getElementById('uploadPrompt').style.display = 'none';
            document.getElementById('fileInfo').style.display = 'block';

            // Show preview
            const reader = new FileReader();
            reader.onload = function(e) {
                const preview = document.getElementById('filePreview');
                const previewImg = document.getElementById('previewImage');

                if (file.type.startsWith('image/')) {
                    previewImg.src = e.target.result;
                    preview.style.display = 'block';
                } else if (file.type.startsWith('video/')) {
                    // For video, show first frame or placeholder
                    previewImg.src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzMzMyIvPjx0ZXh0IHg9IjUwJSIgeT0iNTAlIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMTYiIGZpbGw9IiNmZmYiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGR5PSIuM2VtIj5WaWRlbzwvdGV4dD48L3N2Zz4=';
                    preview.style.display = 'block';
                } else {
                    preview.style.display = 'none';
                }
            };
            reader.readAsDataURL(file);
            setAIValuationState('unavailable', {
                message: 'Complete every required field, then authorize the upload to request AI value guidance.'
            });
            updatePublishReadiness();
        }

        async function handleUpload() {
            if (uploading) return;

            const title = normalizeArtworkTitle(document.getElementById('artTitle').value);
            const price = document.getElementById('artPrice').value;
            const description = document.getElementById('artDescription').value.trim();

            const fileError = validateArtworkFile(selectedFile);
            if (fileError) {
                setFileValidationError(fileError.message);
                alert(fileError.message);
                return;
            }

            if (!selectedAuctionDuration) {
                document.getElementById('auctionDurationError').style.display = 'block';
                document.getElementById('auctionDurationLabel').scrollIntoView({ behavior: 'auto', block: 'center' });
                alert('Choose a 24, 36, or 48 hour auction duration before publishing.');
                return;
            }

            if (!document.getElementById('originalWorkConfirm').checked) {
                document.getElementById('originalWorkError').style.display = 'block';
                document.getElementById('beforePublishTitle').scrollIntoView({ behavior: 'auto', block: 'center' });
                alert('Confirm that this is your original work before publishing.');
                return;
            }

            const validationError = validateArtworkDetails({ title, description, price });
            if (validationError) {
                alert(validationError);
                return;
            }

            if (!updatePublishReadiness()) {
                alert(document.getElementById('publishReadinessHint')?.textContent || 'Complete every required step before publishing.');
                return;
            }

            const walletAddress = window.getCurrentWalletAddress?.();
            if (!walletAddress) {
                alert('Connect your wallet before publishing this artwork.');
                return;
            }
            const chainId = Number(window.getCurrentChainId?.() || window.ArtSoulContracts?.currentNetwork?.chainId || 0);
            if (chainId && chainId !== BASE_SEPOLIA_CHAIN_ID) {
                alert('This artwork must be published on Base Sepolia. Switch networks and try again.');
                return;
            }

            uploading = true;
            publishNavigationLocked = true;
            const uploadBtn = document.getElementById('publishBtn');
            const originalMarkup = uploadBtn.innerHTML;
            setTransactionButtonProcessing(uploadBtn);
            let pendingArtwork = null;

            try {
                // Authorization and AI guidance are completed before Publish is enabled.
                const isAuth = await (
                    window.SupabaseAuth?.isAuthenticatedForWallet?.(walletAddress) ||
                    window.SupabaseAuth?.isAuthenticated?.(walletAddress)
                );
                if (!isAuth || authorizedWalletAddress !== walletAddress.toLowerCase()) {
                    throw createUploadError('AUTHORIZATION_REQUIRED', 'Authorize this upload with your wallet signature before publishing.');
                }
                if (!latestAIValuation || latestAIValuationFormKey !== getAIValuationFormKey()) {
                    throw createUploadError('AI_UNAVAILABLE', 'AI value guidance is not ready. Request an estimate before publishing.');
                }

                // Step 1: Generate file hash for duplicate detection
                currentPublishStage = 'fingerprint';
                setTransactionButtonProcessing(uploadBtn, 'Preparing artwork fingerprint...');
                const fileHash = await window.IPFSClient.generateFileHash(selectedFile);
                console.log('📝 File hash:', fileHash);

                // Step 2: Prepare media storage
                currentPublishStage = 'media_upload';
                setTransactionButtonProcessing(uploadBtn, 'Preparing media...');
                const fileUpload = await window.IPFSClient.uploadFile(selectedFile);
                pendingArtwork = createPendingArtworkDraft({
                    walletAddress,
                    title,
                    description,
                    price,
                    fileHash,
                    fileUpload
                });
                console.log('📤 File uploaded:', fileUpload.ipfsHash);

                // Step 3: Create artwork details
                setTransactionButtonProcessing(uploadBtn, 'Preparing artwork details...');
                const metadata = window.IPFSClient.createMetadata({
                    title: title,
                    description: description,
                    imageUrl: fileUpload.url,
                    mediaType: selectedFile.type,
                    creator: walletAddress,
                    creatorValue: price,
                    aiGuidance: latestAIValuation,
                    createdAt: new Date().toISOString()
                });

                // Step 4: Store artwork metadata
                currentPublishStage = 'metadata_upload';
                const metadataUpload = await window.IPFSClient.uploadMetadata(metadata);
                if (!metadataUpload?.url) {
                    throw new Error('Metadata upload failed before on-chain registration.');
                }
                if (metadataUpload.debug_mock) {
                    console.warn('Debug mock metadata URI enabled for this upload.');
                }
                pendingArtwork = {
                    ...pendingArtwork,
                    stage: 'metadata_prepared',
                    metadata_uri: metadataUpload.url,
                    metadata_hash: metadataUpload.ipfsHash || '',
                    metadata_path: metadataUpload.path || ''
                };
                console.log('📤 Metadata uploaded:', metadataUpload.ipfsHash);

                // Step 5: Initialize contracts
                currentPublishStage = 'wallet_init';
                setTransactionButtonProcessing(uploadBtn, 'Connecting wallet...');
                if (!window.ArtSoulContracts.marketplaceContract) {
                    const provider = await window.web3Modal?.getWalletProvider();
                    if (!provider) throw new Error('No wallet provider');
                    await window.ArtSoulContracts.init(provider);
                }

                // Step 6: Register artwork with the protocol
                currentPublishStage = 'register';
                setTransactionButtonProcessing(uploadBtn, 'Registering artwork...');
                const result = await window.ArtSoulContracts.uploadArtwork(
                    fileUpload.ipfsHash,
                    metadataUpload.url,
                    fileHash,
                    price,
                    {
                        onSubmitted: (registerTxHash) => {
                            pendingArtwork = savePendingArtwork({
                                ...pendingArtwork,
                                register_tx_hash: registerTxHash || '',
                                stage: 'register_submitted',
                                lifecycle_label: 'Finalizing...',
                                lifecycle_message: 'Registration was submitted. Waiting for blockchain confirmation.'
                            });
                        }
                    }
                );

                console.log(' Artwork created! ID:', result.artworkId);
                if (!result?.txHash || !result?.artworkId) {
                    throw new Error('Register transaction did not return a confirmed artwork id.');
                }
                pendingArtwork = savePendingArtwork({
                    ...pendingArtwork,
                    id: `pending:${result.artworkId || pendingArtwork.temp_id}`,
                    artwork_id: result.artworkId ? String(result.artworkId) : '',
                    blockchain_id: result.artworkId ? String(result.artworkId) : '',
                    register_tx_hash: result.txHash || '',
                    register_receipt_status: 1,
                    stage: 'registered',
                    lifecycle_label: 'Finalizing...',
                    lifecycle_message: 'Register transaction confirmed. Waiting for the public artwork page to update.'
                });

                // Step 8: Indexer projection replaces legacy browser writes.
                setTransactionButtonProcessing(uploadBtn, 'Finalizing...');
                console.log('Legacy artwork DB write skipped; v41 indexer will project registration.', {
                    artworkId: result.artworkId,
                    txHash: result.txHash,
                    network: window.ArtSoulContracts.currentNetwork
                });

                // Step 7: Create the initial auction using the required creator-selected duration.
                currentPublishStage = 'auction';
                setTransactionButtonProcessing(uploadBtn, 'Launching auction...');
                let auctionCreated = false;
                let dbSynced = false;
                try {
                    const auctionTxHash = await window.ArtSoulContracts.createAuction(
                        result.artworkId,
                        price,
                        selectedAuctionDuration,
                        {
                            onSubmitted: (submittedAuctionTxHash) => {
                                pendingArtwork = savePendingArtwork({
                                    ...pendingArtwork,
                                    auction_tx_hash: submittedAuctionTxHash || '',
                                    stage: 'auction_submitted',
                                    lifecycle_label: 'Finalizing...',
                                    lifecycle_message: 'Registration is confirmed and the auction was submitted. Waiting for blockchain confirmation.'
                                });
                            }
                        }
                    );
                    auctionCreated = true;
                    pendingArtwork = savePendingArtwork({
                        ...pendingArtwork,
                        auction_tx_hash: auctionTxHash || '',
                        auction_receipt_status: 1,
                        stage: 'auction_created',
                        lifecycle_label: 'Finalizing...',
                        lifecycle_message: 'Register and auction transactions confirmed. Waiting for the public artwork page to update.'
                    });
                    console.log(' Auction created on blockchain');

                    dbSynced = true;
                    console.log('Legacy auction DB sync skipped; v41 indexer will project auction state.');
                } catch (auctionError) {
                    console.error(' Auction creation error:', auctionError);
                    const mappedAuctionError = mapPublishError(auctionError);
                    console.log('Auction creation error shown to user:', mappedAuctionError.message);
                    pendingArtwork = savePendingArtwork({
                        ...pendingArtwork,
                        stage: 'auction_failed',
                        lifecycle_label: 'Artwork registered - auction failed',
                        lifecycle_message: 'The artwork is registered on-chain, but auction creation failed. You can retry auction from your profile.',
                        auction_error_code: mappedAuctionError.code,
                        auction_error_message: mappedAuctionError.message
                    });

                    if (auctionCreated && !dbSynced) {
                        // Blockchain succeeded but database failed after retries
                        await alert('Auction created on blockchain but database sync failed.\n\nYour artwork is live on the blockchain!\nPlease go to your profile and the status will sync automatically.');
                        window.location.href = 'profile.html';
                        return;
                    } else if (!auctionCreated) {
                        // Blockchain creation failed - artwork stays as draft
                        await alert(`Artwork registered - auction failed.\n\n${mappedAuctionError.message}\n\nYou can retry auction from your profile.`);
                        window.location.href = 'profile.html';
                        return;
                    }
                }

                // Success - redirect to the new artwork detail page.
                const chainId = window.getCurrentChainId?.() || window.ArtSoulContracts?.chainId || 84532;
                window.location.href = `artwork.html?id=v41:${chainId}:${result.artworkId}`;

            } catch (error) {
                console.error('Publish failed:', error);
                const mapped = mapPublishError(error);
                const errorMessage = `Publish failed: ${mapped.message}`;

                if (pendingArtwork?.register_tx_hash && !pendingArtwork?.artwork_id) {
                    removePendingArtwork(pendingArtwork.temp_id);
                }

                console.log('Publish error shown to user:', errorMessage);
                alert(errorMessage);
            } finally {
                publishNavigationLocked = false;
                uploading = false;
                currentPublishStage = 'idle';
                restoreTransactionButton(uploadBtn, originalMarkup);
            }
        }

        function handleUploadFormChange() {
            if (latestAIValuation && latestAIValuationFormKey !== getAIValuationFormKey()) {
                latestAIValuation = null;
                latestAIValuationFormKey = '';
                setAIValuationState('unavailable', {
                    message: 'Artwork details changed. Request updated AI value guidance before publishing.'
                });
            }
            updateAIValuationRetryState();
            updatePublishReadiness();
        }

        function bindUploadFlow() {
            ['artTitle', 'artDescription', 'artPrice'].forEach((id) => {
                const field = document.getElementById(id);
                field?.addEventListener('input', updatePublishReadiness);
                field?.addEventListener('change', handleUploadFormChange);
            });
            document.getElementById('originalWorkConfirm')?.addEventListener('change', handleUploadFormChange);
            window.addEventListener('artsoul:wallet-state-changed', (event) => {
                const nextAddress = String(event?.detail?.address || '').toLowerCase();
                if (!event?.detail?.isConnected || (authorizedWalletAddress && nextAddress !== authorizedWalletAddress)) {
                    authorizedWalletAddress = '';
                }
                updatePublishReadiness();
            });
            window.addEventListener('beforeunload', (event) => {
                if (!publishNavigationLocked) return;
                event.preventDefault();
                event.returnValue = '';
            });
            updateAIValuationRetryState();
            updatePublishReadiness();
        }

        bindUploadFlow();

Object.assign(window, {
    handleFileSelect,
    retryAIValuation,
    beginPrePublishFlow,
    selectAuctionDuration,
    clearOriginalWorkError,
    handleUpload
});
