-- A8a moderation passkey step-up foundation (additive only).
-- Founder decisions 2026-07-20: 15-minute step-up sessions, one one-time
-- auditable bootstrap grant, Safe-only founder recovery (not implemented
-- here; recovery fails closed), X/Discord are never authentication factors.
--
-- These tables are service-role-only. No existing production table is
-- altered or dropped. Only PUBLIC credential material is ever stored:
-- WebAuthn private keys never leave the authenticator.

-- 1) Registered staff passkeys (multiple per wallet, revocable).
CREATE TABLE IF NOT EXISTS public.artsoul_staff_passkeys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT NOT NULL,
    credential_id TEXT NOT NULL UNIQUE,
    -- Base64url COSE public key returned by WebAuthn registration.
    public_key TEXT NOT NULL,
    sign_count BIGINT NOT NULL DEFAULT 0,
    transports TEXT,
    aaguid TEXT,
    label TEXT,
    enrolled_via TEXT NOT NULL CHECK (enrolled_via IN ('bootstrap', 'additional')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by TEXT,
    CHECK (wallet_address = LOWER(wallet_address)),
    CHECK (wallet_address ~ '^0x[0-9a-f]{40}$'),
    CHECK (revoked_by IS NULL OR revoked_by ~ '^0x[0-9a-f]{40}$')
);

CREATE INDEX IF NOT EXISTS idx_artsoul_staff_passkeys_wallet_active
    ON public.artsoul_staff_passkeys (wallet_address)
    WHERE revoked_at IS NULL;

-- 2) One-time WebAuthn challenges with purpose and expiry.
CREATE TABLE IF NOT EXISTS public.artsoul_webauthn_challenges (
    challenge TEXT PRIMARY KEY,
    wallet_address TEXT NOT NULL,
    purpose TEXT NOT NULL CHECK (purpose IN ('registration', 'authentication')),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (wallet_address = LOWER(wallet_address)),
    CHECK (wallet_address ~ '^0x[0-9a-f]{40}$')
);

CREATE INDEX IF NOT EXISTS idx_artsoul_webauthn_challenges_expiry
    ON public.artsoul_webauthn_challenges (expires_at);

-- 3) One-time enrollment grants. Exactly one 'bootstrap' grant can ever
--    exist (partial unique index), making the founder bootstrap runbook
--    safe to run once and fail on reuse.
CREATE TABLE IF NOT EXISTS public.artsoul_staff_enrollment_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_wallet TEXT NOT NULL,
    purpose TEXT NOT NULL CHECK (purpose IN ('bootstrap', 'additional')),
    issued_by TEXT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    consumed_by_credential TEXT,
    CHECK (target_wallet = LOWER(target_wallet)),
    CHECK (target_wallet ~ '^0x[0-9a-f]{40}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_artsoul_enrollment_grants_single_bootstrap
    ON public.artsoul_staff_enrollment_grants (purpose)
    WHERE purpose = 'bootstrap';

CREATE INDEX IF NOT EXISTS idx_artsoul_enrollment_grants_target
    ON public.artsoul_staff_enrollment_grants (target_wallet)
    WHERE consumed_at IS NULL;

-- 4) Append-only staff auth/audit events. No raw IP addresses and no full
--    user-agent strings are stored in this phase.
CREATE TABLE IF NOT EXISTS public.artsoul_staff_auth_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT,
    event_type TEXT NOT NULL CHECK (event_type IN (
        'passkey_enrolled',
        'passkey_auth_success',
        'passkey_auth_failure',
        'passkey_revoked',
        'grant_issued',
        'grant_consumed',
        'recovery_denied'
    )),
    credential_id TEXT,
    details JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (wallet_address IS NULL OR wallet_address ~ '^0x[0-9a-f]{40}$')
);

CREATE INDEX IF NOT EXISTS idx_artsoul_staff_auth_events_wallet
    ON public.artsoul_staff_auth_events (wallet_address, created_at DESC);

-- RLS: service-role only, mirroring phase18 moderation tables.
ALTER TABLE public.artsoul_staff_passkeys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_webauthn_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_staff_enrollment_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_staff_auth_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.artsoul_staff_passkeys FORCE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_webauthn_challenges FORCE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_staff_enrollment_grants FORCE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_staff_auth_events FORCE ROW LEVEL SECURITY;

REVOKE ALL ON public.artsoul_staff_passkeys FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.artsoul_webauthn_challenges FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.artsoul_staff_enrollment_grants FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.artsoul_staff_auth_events FROM PUBLIC, anon, authenticated;

GRANT ALL ON public.artsoul_staff_passkeys TO service_role;
GRANT ALL ON public.artsoul_webauthn_challenges TO service_role;
GRANT ALL ON public.artsoul_staff_enrollment_grants TO service_role;
GRANT ALL ON public.artsoul_staff_auth_events TO service_role;

GRANT USAGE, SELECT ON SEQUENCE public.artsoul_staff_passkeys_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.artsoul_staff_enrollment_grants_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.artsoul_staff_auth_events_id_seq TO service_role;
