-- A8a moderation passkey step-up foundation (additive only).
-- Founder decisions 2026-07-20: 15-minute step-up sessions, one one-time
-- auditable bootstrap grant, Safe-only founder recovery (not implemented
-- here; recovery fails closed), X/Discord are never authentication factors.
--
-- These tables are service-role-only. No existing production table is
-- altered or dropped, and no historical migration is edited. Only PUBLIC
-- credential material is ever stored: WebAuthn private keys never leave the
-- authenticator. Enrollment grants store ONLY a SHA-256 hash of a one-time
-- bearer token; the raw token is never persisted.
--
-- All successful state transitions run through the SECURITY DEFINER RPCs at
-- the bottom of this file so credential, grant, and audit writes are atomic.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1) Registered staff passkeys (multiple per wallet, revocable).
CREATE TABLE IF NOT EXISTS public.artsoul_staff_passkeys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT NOT NULL,
    credential_id TEXT NOT NULL UNIQUE,
    -- Base64url COSE public key returned by WebAuthn registration.
    public_key TEXT NOT NULL,
    sign_count BIGINT NOT NULL DEFAULT 0,
    transports TEXT,
    aaguid TEXT,
    label TEXT,
    enrolled_via TEXT NOT NULL CHECK (enrolled_via IN ('bootstrap', 'additional')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by TEXT,
    CHECK (wallet_address = LOWER(wallet_address)),
    CHECK (wallet_address ~ '^0x[0-9a-f]{40}$'),
    CHECK (revoked_by IS NULL OR revoked_by ~ '^0x[0-9a-f]{40}$')
);

CREATE INDEX IF NOT EXISTS idx_artsoul_staff_passkeys_wallet_active
    ON public.artsoul_staff_passkeys (wallet_address)
    WHERE revoked_at IS NULL;

-- 2) One-time enrollment grants. Each stores ONLY the SHA-256 hash of a
--    one-time bearer token, plus purpose, expiry, and consumed/revoked
--    state. At most one ACTIVE (unconsumed, unrevoked) bootstrap grant may
--    exist at a time; an expired unused one can be superseded (revoked)
--    before a replacement is issued. The "never a second bootstrap after
--    one is consumed" rule is enforced in the issue RPC, not by an index
--    that would make an expired unused grant impossible to replace.
CREATE TABLE IF NOT EXISTS public.artsoul_staff_enrollment_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_wallet TEXT NOT NULL,
    purpose TEXT NOT NULL CHECK (purpose IN ('bootstrap', 'additional')),
    token_hash TEXT NOT NULL,
    issued_by TEXT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    consumed_by_credential TEXT,
    revoked_at TIMESTAMPTZ,
    superseded_by BIGINT,
    CHECK (target_wallet = LOWER(target_wallet)),
    CHECK (target_wallet ~ '^0x[0-9a-f]{40}$')
);

-- At most one ACTIVE unconsumed, unrevoked bootstrap grant. An expired but
-- unrevoked grant still occupies the slot until the operator supersedes it,
-- which is the intended auditable replacement path.
CREATE UNIQUE INDEX IF NOT EXISTS idx_artsoul_enrollment_grants_active_bootstrap
    ON public.artsoul_staff_enrollment_grants (purpose)
    WHERE purpose = 'bootstrap' AND consumed_at IS NULL AND revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_artsoul_enrollment_grants_target
    ON public.artsoul_staff_enrollment_grants (target_wallet)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;

-- 3) One-time WebAuthn challenges with purpose and expiry. Registration
--    challenges are bound to the exact grant id they were issued for.
CREATE TABLE IF NOT EXISTS public.artsoul_webauthn_challenges (
    challenge TEXT PRIMARY KEY,
    wallet_address TEXT NOT NULL,
    purpose TEXT NOT NULL CHECK (purpose IN ('registration', 'authentication')),
    grant_id BIGINT,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (wallet_address = LOWER(wallet_address)),
    CHECK (wallet_address ~ '^0x[0-9a-f]{40}$')
);

CREATE INDEX IF NOT EXISTS idx_artsoul_webauthn_challenges_expiry
    ON public.artsoul_webauthn_challenges (expires_at);

-- 4) Append-only staff auth/audit events. No raw IP addresses and no full
--    user-agent strings are stored in this phase.
CREATE TABLE IF NOT EXISTS public.artsoul_staff_auth_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT,
    event_type TEXT NOT NULL CHECK (event_type IN (
        'passkey_enrolled',
        'passkey_auth_success',
        'passkey_auth_failure',
        'passkey_revoked',
        'passkey_revoke_denied',
        'grant_issued',
        'grant_consumed',
        'grant_superseded',
        'recovery_denied'
    )),
    credential_id TEXT,
    details JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (wallet_address IS NULL OR wallet_address ~ '^0x[0-9a-f]{40}$')
);

CREATE INDEX IF NOT EXISTS idx_artsoul_staff_auth_events_wallet
    ON public.artsoul_staff_auth_events (wallet_address, created_at DESC);

-- RLS: service-role only, mirroring the phase18 moderation tables.
ALTER TABLE public.artsoul_staff_passkeys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_webauthn_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_staff_enrollment_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_staff_auth_events ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.artsoul_staff_passkeys FORCE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_webauthn_challenges FORCE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_staff_enrollment_grants FORCE ROW LEVEL SECURITY;
ALTER TABLE public.artsoul_staff_auth_events FORCE ROW LEVEL SECURITY;

REVOKE ALL ON public.artsoul_staff_passkeys FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.artsoul_webauthn_challenges FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.artsoul_staff_enrollment_grants FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.artsoul_staff_auth_events FROM PUBLIC, anon, authenticated;

GRANT ALL ON public.artsoul_staff_passkeys TO service_role;
GRANT ALL ON public.artsoul_webauthn_challenges TO service_role;
GRANT ALL ON public.artsoul_staff_enrollment_grants TO service_role;
GRANT ALL ON public.artsoul_staff_auth_events TO service_role;

GRANT USAGE, SELECT ON SEQUENCE public.artsoul_staff_passkeys_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.artsoul_staff_enrollment_grants_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.artsoul_staff_auth_events_id_seq TO service_role;

-- ===========================================================================
-- Atomic state-transition RPCs. Cryptographic verification stays in
-- @simplewebauthn/server; these functions receive already-verified public
-- results and perform the single-transaction database mutation. Each is
-- SECURITY DEFINER with a fixed search_path, uses no user-controlled SQL
-- identifiers, returns an explicit result code, and rolls the whole
-- operation back if any insert/update fails.
-- ===========================================================================

-- Issue an enrollment grant (additional device via HTTP step-up, or a
-- bootstrap grant from the founder-operated runbook). Returns the new grant
-- id on success; raises with an explicit code otherwise.
CREATE OR REPLACE FUNCTION public.a8a_issue_enrollment_grant(
    p_target_wallet TEXT,
    p_purpose TEXT,
    p_issued_by TEXT,
    p_token_hash TEXT,
    p_expires_at TIMESTAMPTZ
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_wallet TEXT := LOWER(p_target_wallet);
    v_existing RECORD;
    v_new_id BIGINT;
BEGIN
    IF v_wallet !~ '^0x[0-9a-f]{40}$' THEN
        RAISE EXCEPTION 'A8A_INVALID_WALLET';
    END IF;
    IF p_purpose NOT IN ('bootstrap', 'additional') THEN
        RAISE EXCEPTION 'A8A_INVALID_PURPOSE';
    END IF;
    IF p_token_hash IS NULL OR LENGTH(p_token_hash) < 32 THEN
        RAISE EXCEPTION 'A8A_INVALID_TOKEN_HASH';
    END IF;

    IF p_purpose = 'bootstrap' THEN
        -- Once a bootstrap grant is consumed or a bootstrap credential
        -- exists, no further bootstrap grant may ever be issued.
        IF EXISTS (
            SELECT 1 FROM public.artsoul_staff_enrollment_grants
            WHERE purpose = 'bootstrap' AND consumed_at IS NOT NULL
        ) OR EXISTS (
            SELECT 1 FROM public.artsoul_staff_passkeys
            WHERE enrolled_via = 'bootstrap' AND revoked_at IS NULL
        ) THEN
            RAISE EXCEPTION 'A8A_BOOTSTRAP_ALREADY_ESTABLISHED';
        END IF;

        -- Supersede an existing active bootstrap grant only if it is expired
        -- and unused; an active unexpired one blocks a duplicate.
        SELECT * INTO v_existing
        FROM public.artsoul_staff_enrollment_grants
        WHERE purpose = 'bootstrap' AND consumed_at IS NULL AND revoked_at IS NULL
        FOR UPDATE;

        IF FOUND THEN
            IF v_existing.expires_at > NOW() THEN
                RAISE EXCEPTION 'A8A_ACTIVE_BOOTSTRAP_EXISTS';
            END IF;
            UPDATE public.artsoul_staff_enrollment_grants
            SET revoked_at = NOW()
            WHERE id = v_existing.id;
            INSERT INTO public.artsoul_staff_auth_events (wallet_address, event_type, details)
            VALUES (v_wallet, 'grant_superseded',
                    JSONB_BUILD_OBJECT('superseded_grant_id', v_existing.id, 'reason', 'expired_unused_bootstrap'));
        END IF;
    END IF;

    INSERT INTO public.artsoul_staff_enrollment_grants (
        target_wallet, purpose, token_hash, issued_by, expires_at
    ) VALUES (
        v_wallet, p_purpose, p_token_hash, LOWER(p_issued_by), p_expires_at
    )
    RETURNING id INTO v_new_id;

    IF v_existing.id IS NOT NULL THEN
        UPDATE public.artsoul_staff_enrollment_grants
        SET superseded_by = v_new_id
        WHERE id = v_existing.id;
    END IF;

    INSERT INTO public.artsoul_staff_auth_events (wallet_address, event_type, details)
    VALUES (v_wallet, 'grant_issued',
            JSONB_BUILD_OBJECT('grant_id', v_new_id, 'purpose', p_purpose, 'issued_by', LOWER(p_issued_by)));

    RETURN v_new_id;
END;
$$;

-- Complete a verified registration atomically: validate + consume the exact
-- grant and its bound challenge, insert the credential, and write the
-- grant_consumed + passkey_enrolled audit events. Returns 'OK' or raises.
CREATE OR REPLACE FUNCTION public.a8a_complete_registration(
    p_grant_id BIGINT,
    p_token_hash TEXT,
    p_wallet TEXT,
    p_purpose TEXT,
    p_challenge TEXT,
    p_credential_id TEXT,
    p_public_key TEXT,
    p_sign_count BIGINT,
    p_transports TEXT,
    p_aaguid TEXT,
    p_label TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_wallet TEXT := LOWER(p_wallet);
    v_grant RECORD;
    v_challenge RECORD;
BEGIN
    SELECT * INTO v_grant
    FROM public.artsoul_staff_enrollment_grants
    WHERE id = p_grant_id
    FOR UPDATE;

    IF NOT FOUND
        OR v_grant.target_wallet <> v_wallet
        OR v_grant.purpose <> p_purpose
        OR v_grant.token_hash <> p_token_hash
        OR v_grant.consumed_at IS NOT NULL
        OR v_grant.revoked_at IS NOT NULL
        OR v_grant.expires_at <= NOW() THEN
        RETURN 'GRANT_INVALID';
    END IF;

    SELECT * INTO v_challenge
    FROM public.artsoul_webauthn_challenges
    WHERE challenge = p_challenge
    FOR UPDATE;

    IF NOT FOUND
        OR v_challenge.wallet_address <> v_wallet
        OR v_challenge.purpose <> 'registration'
        OR v_challenge.grant_id IS DISTINCT FROM p_grant_id
        OR v_challenge.consumed_at IS NOT NULL
        OR v_challenge.expires_at <= NOW() THEN
        RETURN 'CHALLENGE_INVALID';
    END IF;

    IF p_purpose = 'bootstrap' THEN
        IF EXISTS (
            SELECT 1 FROM public.artsoul_staff_enrollment_grants
            WHERE purpose = 'bootstrap' AND consumed_at IS NOT NULL AND id <> p_grant_id
        ) OR EXISTS (
            SELECT 1 FROM public.artsoul_staff_passkeys
            WHERE enrolled_via = 'bootstrap' AND revoked_at IS NULL
        ) THEN
            RETURN 'BOOTSTRAP_ALREADY_ESTABLISHED';
        END IF;
    END IF;

    UPDATE public.artsoul_webauthn_challenges
    SET consumed_at = NOW()
    WHERE challenge = p_challenge;

    UPDATE public.artsoul_staff_enrollment_grants
    SET consumed_at = NOW(), consumed_by_credential = p_credential_id
    WHERE id = p_grant_id;

    INSERT INTO public.artsoul_staff_passkeys (
        wallet_address, credential_id, public_key, sign_count,
        transports, aaguid, label, enrolled_via
    ) VALUES (
        v_wallet, p_credential_id, p_public_key, COALESCE(p_sign_count, 0),
        p_transports, p_aaguid, p_label, p_purpose
    );

    INSERT INTO public.artsoul_staff_auth_events (wallet_address, event_type, credential_id, details)
    VALUES (v_wallet, 'grant_consumed', p_credential_id,
            JSONB_BUILD_OBJECT('grant_id', p_grant_id, 'purpose', p_purpose));
    INSERT INTO public.artsoul_staff_auth_events (wallet_address, event_type, credential_id, details)
    VALUES (v_wallet, 'passkey_enrolled', p_credential_id,
            JSONB_BUILD_OBJECT('enrolled_via', p_purpose, 'label', p_label));

    RETURN 'OK';
END;
$$;

-- Revoke a credential atomically with last-key protection. Returns 'OK',
-- 'LAST_ACTIVE_CREDENTIAL' (no state change, denial audited), or
-- 'CREDENTIAL_NOT_FOUND'.
CREATE OR REPLACE FUNCTION public.a8a_revoke_credential(
    p_wallet TEXT,
    p_credential_id TEXT,
    p_revoked_by TEXT
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_wallet TEXT := LOWER(p_wallet);
    v_active_count INTEGER;
    v_target RECORD;
BEGIN
    -- Lock all active rows for this wallet to serialize concurrent revokes.
    PERFORM 1 FROM public.artsoul_staff_passkeys
    WHERE wallet_address = v_wallet AND revoked_at IS NULL
    FOR UPDATE;

    SELECT * INTO v_target
    FROM public.artsoul_staff_passkeys
    WHERE wallet_address = v_wallet AND credential_id = p_credential_id AND revoked_at IS NULL;

    IF NOT FOUND THEN
        RETURN 'CREDENTIAL_NOT_FOUND';
    END IF;

    SELECT COUNT(*) INTO v_active_count
    FROM public.artsoul_staff_passkeys
    WHERE wallet_address = v_wallet AND revoked_at IS NULL;

    IF v_active_count <= 1 THEN
        INSERT INTO public.artsoul_staff_auth_events (wallet_address, event_type, credential_id, details)
        VALUES (v_wallet, 'passkey_revoke_denied', p_credential_id,
                JSONB_BUILD_OBJECT('reason', 'last_active_credential'));
        RETURN 'LAST_ACTIVE_CREDENTIAL';
    END IF;

    UPDATE public.artsoul_staff_passkeys
    SET revoked_at = NOW(), revoked_by = v_wallet
    WHERE wallet_address = v_wallet AND credential_id = p_credential_id AND revoked_at IS NULL;

    INSERT INTO public.artsoul_staff_auth_events (wallet_address, event_type, credential_id, details)
    VALUES (v_wallet, 'passkey_revoked', p_credential_id,
            JSONB_BUILD_OBJECT('revoked_by', v_wallet));

    RETURN 'OK';
END;
$$;

-- Complete a verified authentication atomically: reject a stale counter
-- (while allowing authenticators that keep the counter at zero), advance
-- sign_count/last_used_at, and write passkey_auth_success. Returns 'OK',
-- 'STALE_COUNTER', or 'CREDENTIAL_NOT_FOUND'.
CREATE OR REPLACE FUNCTION public.a8a_complete_authentication(
    p_wallet TEXT,
    p_credential_id TEXT,
    p_new_counter BIGINT
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_wallet TEXT := LOWER(p_wallet);
    v_stored BIGINT;
BEGIN
    SELECT sign_count INTO v_stored
    FROM public.artsoul_staff_passkeys
    WHERE wallet_address = v_wallet AND credential_id = p_credential_id AND revoked_at IS NULL
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN 'CREDENTIAL_NOT_FOUND';
    END IF;

    -- Accept a strictly increasing counter, or a zero-counter authenticator
    -- that reports zero on both sides. Anything else is a stale/cloned
    -- counter and is rejected.
    IF NOT (p_new_counter > v_stored OR (p_new_counter = 0 AND v_stored = 0)) THEN
        RETURN 'STALE_COUNTER';
    END IF;

    UPDATE public.artsoul_staff_passkeys
    SET sign_count = p_new_counter, last_used_at = NOW()
    WHERE wallet_address = v_wallet AND credential_id = p_credential_id;

    INSERT INTO public.artsoul_staff_auth_events (wallet_address, event_type, credential_id, details)
    VALUES (v_wallet, 'passkey_auth_success', p_credential_id, NULL);

    RETURN 'OK';
END;
$$;

REVOKE ALL ON FUNCTION public.a8a_issue_enrollment_grant(TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.a8a_complete_registration(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BIGINT, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.a8a_revoke_credential(TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.a8a_complete_authentication(TEXT, TEXT, BIGINT) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.a8a_issue_enrollment_grant(TEXT, TEXT, TEXT, TEXT, TIMESTAMPTZ) TO service_role;
GRANT EXECUTE ON FUNCTION public.a8a_complete_registration(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, BIGINT, TEXT, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.a8a_revoke_credential(TEXT, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.a8a_complete_authentication(TEXT, TEXT, BIGINT) TO service_role;
