-- A8b public artwork-report intake (additive only).
--
-- The public API writes through submit_artwork_report() with the service role.
-- Browser roles cannot read complaint text, reporter wallets, or audit events.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.artwork_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chain_id NUMERIC(78, 0) NOT NULL,
    artwork_id NUMERIC(78, 0) NOT NULL,
    reporter_wallet TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN (
        'copyright',
        'impersonation',
        'prohibited_content',
        'spam',
        'other'
    )),
    details TEXT NOT NULL CHECK (
        LENGTH(TRIM(details)) > 0 AND
        LENGTH(details) <= 2000
    ),
    reference_url TEXT CHECK (
        reference_url IS NULL OR (
            LENGTH(reference_url) <= 500 AND
            reference_url ~* '^https?://'
        )
    ),
    good_faith_confirmed BOOLEAN NOT NULL CHECK (good_faith_confirmed = TRUE),
    status TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN (
        'pending_review',
        'actioned',
        'dismissed',
        'withdrawn'
    )),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (reporter_wallet = LOWER(reporter_wallet)),
    CHECK (reporter_wallet ~ '^0x[0-9a-f]{40}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_artwork_reports_one_pending_category
    ON public.artwork_reports (chain_id, artwork_id, reporter_wallet, category)
    WHERE status = 'pending_review';

CREATE INDEX IF NOT EXISTS idx_artwork_reports_review_queue
    ON public.artwork_reports (status, created_at ASC);

CREATE TABLE IF NOT EXISTS public.artwork_report_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id UUID NOT NULL REFERENCES public.artwork_reports(id) ON DELETE RESTRICT,
    event_type TEXT NOT NULL CHECK (event_type IN ('REPORT_SUBMITTED')),
    actor_wallet TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (actor_wallet = LOWER(actor_wallet)),
    CHECK (actor_wallet ~ '^0x[0-9a-f]{40}$')
);

CREATE INDEX IF NOT EXISTS idx_artwork_report_events_report
    ON public.artwork_report_events (report_id, created_at ASC);

ALTER TABLE public.artwork_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_reports FORCE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_report_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_report_events FORCE ROW LEVEL SECURITY;

REVOKE ALL ON public.artwork_reports FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.artwork_report_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.artwork_reports TO service_role;
GRANT ALL ON public.artwork_report_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.artwork_report_events_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.submit_artwork_report(
    p_chain_id NUMERIC,
    p_artwork_id NUMERIC,
    p_reporter_wallet TEXT,
    p_category TEXT,
    p_details TEXT,
    p_reference_url TEXT,
    p_good_faith_confirmed BOOLEAN
)
RETURNS TABLE (
    report_id UUID,
    report_status TEXT,
    report_created_at TIMESTAMPTZ,
    already_submitted BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    normalized_wallet TEXT := LOWER(TRIM(COALESCE(p_reporter_wallet, '')));
    normalized_category TEXT := LOWER(TRIM(COALESCE(p_category, '')));
    normalized_details TEXT := TRIM(COALESCE(p_details, ''));
    normalized_reference_url TEXT := NULLIF(TRIM(COALESCE(p_reference_url, '')), '');
    inserted_report public.artwork_reports%ROWTYPE;
    existing_report public.artwork_reports%ROWTYPE;
BEGIN
    IF p_chain_id NOT IN (84532, 11155111) THEN
        RAISE EXCEPTION 'Unsupported artwork chain';
    END IF;

    IF p_artwork_id IS NULL OR p_artwork_id <= 0 THEN
        RAISE EXCEPTION 'Invalid artwork id';
    END IF;

    IF normalized_wallet !~ '^0x[0-9a-f]{40}$' THEN
        RAISE EXCEPTION 'Invalid reporter wallet';
    END IF;

    IF normalized_category NOT IN (
        'copyright',
        'impersonation',
        'prohibited_content',
        'spam',
        'other'
    ) THEN
        RAISE EXCEPTION 'Invalid report category';
    END IF;

    IF LENGTH(normalized_details) = 0 OR LENGTH(normalized_details) > 2000 THEN
        RAISE EXCEPTION 'Report details are required and must not exceed 2000 characters';
    END IF;

    IF normalized_reference_url IS NOT NULL AND (
        LENGTH(normalized_reference_url) > 500 OR
        normalized_reference_url !~* '^https?://'
    ) THEN
        RAISE EXCEPTION 'Reference URL must be an HTTP or HTTPS URL';
    END IF;

    IF p_good_faith_confirmed IS DISTINCT FROM TRUE THEN
        RAISE EXCEPTION 'Good-faith confirmation is required';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.v41_artworks AS artwork
        WHERE artwork.chain_id = p_chain_id
          AND artwork.artwork_id = p_artwork_id
    ) THEN
        RAISE EXCEPTION 'Artwork not found';
    END IF;

    INSERT INTO public.artwork_reports (
        chain_id,
        artwork_id,
        reporter_wallet,
        category,
        details,
        reference_url,
        good_faith_confirmed
    ) VALUES (
        p_chain_id,
        p_artwork_id,
        normalized_wallet,
        normalized_category,
        normalized_details,
        normalized_reference_url,
        TRUE
    )
    ON CONFLICT (chain_id, artwork_id, reporter_wallet, category)
        WHERE status = 'pending_review'
    DO NOTHING
    RETURNING * INTO inserted_report;

    IF inserted_report.id IS NULL THEN
        SELECT report.*
        INTO existing_report
        FROM public.artwork_reports AS report
        WHERE report.chain_id = p_chain_id
          AND report.artwork_id = p_artwork_id
          AND report.reporter_wallet = normalized_wallet
          AND report.category = normalized_category
          AND report.status = 'pending_review'
        ORDER BY report.created_at DESC
        LIMIT 1;

        RETURN QUERY SELECT
            existing_report.id,
            existing_report.status,
            existing_report.created_at,
            TRUE;
        RETURN;
    END IF;

    INSERT INTO public.artwork_report_events (
        report_id,
        event_type,
        actor_wallet
    ) VALUES (
        inserted_report.id,
        'REPORT_SUBMITTED',
        normalized_wallet
    );

    RETURN QUERY SELECT
        inserted_report.id,
        inserted_report.status,
        inserted_report.created_at,
        FALSE;
END;
$$;

REVOKE ALL ON FUNCTION public.submit_artwork_report(
    NUMERIC,
    NUMERIC,
    TEXT,
    TEXT,
    TEXT,
    TEXT,
    BOOLEAN
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_artwork_report(
    NUMERIC,
    NUMERIC,
    TEXT,
    TEXT,
    TEXT,
    TEXT,
    BOOLEAN
) TO service_role;
