-- A8c Protocol Admin review workflow (additive, feature-flagged).
--
-- This migration is not an activation instruction. Apply it only through the
-- reviewed A8 rollout runbook. Browser roles cannot read complaint, audit, or
-- notification data; the server uses service_role after SIWE + role + passkey.

ALTER TABLE public.artwork_reports
    ADD COLUMN IF NOT EXISTS reviewed_by TEXT,
    ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS decision_reason TEXT;

ALTER TABLE public.artwork_reports
    DROP CONSTRAINT IF EXISTS artwork_reports_reviewed_by_check;
ALTER TABLE public.artwork_reports
    ADD CONSTRAINT artwork_reports_reviewed_by_check CHECK (
        reviewed_by IS NULL OR (
            reviewed_by = LOWER(reviewed_by) AND
            reviewed_by ~ '^0x[0-9a-f]{40}$'
        )
    );

ALTER TABLE public.artwork_reports
    DROP CONSTRAINT IF EXISTS artwork_reports_decision_reason_check;
ALTER TABLE public.artwork_reports
    ADD CONSTRAINT artwork_reports_decision_reason_check CHECK (
        decision_reason IS NULL OR (
            LENGTH(TRIM(decision_reason)) > 0 AND
            LENGTH(decision_reason) <= 500
        )
    );

ALTER TABLE public.artwork_report_events
    ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE public.artwork_report_events
    DROP CONSTRAINT IF EXISTS artwork_report_events_event_type_check;
ALTER TABLE public.artwork_report_events
    ADD CONSTRAINT artwork_report_events_event_type_check CHECK (event_type IN (
        'REPORT_SUBMITTED',
        'REPORT_HIDDEN',
        'REPORT_DISMISSED',
        'REPORT_REOPENED',
        'REPORT_RESOLVED',
        'REPORT_RESTORED',
        'NOTIFICATION_QUEUED'
    ));
ALTER TABLE public.artwork_report_events
    DROP CONSTRAINT IF EXISTS artwork_report_events_reason_check;
ALTER TABLE public.artwork_report_events
    ADD CONSTRAINT artwork_report_events_reason_check CHECK (
        reason IS NULL OR (
            LENGTH(TRIM(reason)) > 0 AND
            LENGTH(reason) <= 500
        )
    );

CREATE TABLE IF NOT EXISTS public.artwork_report_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id UUID NOT NULL REFERENCES public.artwork_reports(id) ON DELETE RESTRICT,
    recipient_wallet TEXT NOT NULL,
    notification_type TEXT NOT NULL CHECK (notification_type IN (
        'REPORT_ACTIONED',
        'REPORT_DISMISSED',
        'REPORT_REOPENED',
        'ARTWORK_HIDDEN',
        'ARTWORK_RESTORED'
    )),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    read_at TIMESTAMPTZ,
    CHECK (recipient_wallet = LOWER(recipient_wallet)),
    CHECK (recipient_wallet ~ '^0x[0-9a-f]{40}$')
);

CREATE INDEX IF NOT EXISTS idx_artwork_report_notifications_recipient
    ON public.artwork_report_notifications (recipient_wallet, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_artwork_report_notifications_report
    ON public.artwork_report_notifications (report_id, created_at DESC);

ALTER TABLE public.artwork_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_reports FORCE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_report_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_report_events FORCE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_report_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_report_notifications FORCE ROW LEVEL SECURITY;

REVOKE ALL ON public.artwork_reports FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.artwork_report_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.artwork_report_notifications FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.artwork_reports TO service_role;
GRANT ALL ON public.artwork_report_events TO service_role;
GRANT ALL ON public.artwork_report_notifications TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.artwork_report_notifications_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.review_artwork_report(
    p_report_id UUID,
    p_expected_updated_at TIMESTAMPTZ,
    p_action TEXT,
    p_reason TEXT,
    p_actor_wallet TEXT
)
RETURNS TABLE (
    report_id UUID,
    report_status TEXT,
    report_updated_at TIMESTAMPTZ,
    artwork_hidden BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    current_report public.artwork_reports%ROWTYPE;
    normalized_action TEXT := LOWER(TRIM(COALESCE(p_action, '')));
    normalized_reason TEXT := TRIM(COALESCE(p_reason, ''));
    normalized_actor TEXT := LOWER(TRIM(COALESCE(p_actor_wallet, '')));
    creator_wallet TEXT;
    next_status TEXT;
    event_name TEXT;
    reporter_notification TEXT;
    creator_notification TEXT;
    new_updated_at TIMESTAMPTZ;
    artwork_still_hidden BOOLEAN := FALSE;
    other_actioned_reports BIGINT := 0;
BEGIN
    IF normalized_actor !~ '^0x[0-9a-f]{40}$' THEN
        RAISE EXCEPTION 'Invalid moderation actor wallet';
    END IF;
    IF normalized_action NOT IN ('hide', 'dismiss', 'reopen', 'restore') THEN
        RAISE EXCEPTION 'REPORT_ACTION_NOT_ALLOWED';
    END IF;
    IF LENGTH(normalized_reason) = 0 OR LENGTH(normalized_reason) > 500 THEN
        RAISE EXCEPTION 'A review reason is required and must not exceed 500 characters';
    END IF;

    SELECT report.*
    INTO current_report
    FROM public.artwork_reports AS report
    WHERE report.id = p_report_id
    FOR UPDATE;

    IF current_report.id IS NULL THEN
        RAISE EXCEPTION 'REPORT_NOT_FOUND';
    END IF;
    IF current_report.updated_at IS DISTINCT FROM p_expected_updated_at THEN
        RAISE EXCEPTION 'REPORT_REVIEW_CONFLICT';
    END IF;

    -- Serialize every transition for one artwork while preserving each
    -- reporter's independent row and history. This prevents two moderators
    -- from racing hide/restore decisions across separate reports.
    PERFORM pg_advisory_xact_lock(hashtextextended(
        'artsoul-review:' || current_report.chain_id::TEXT || ':' || current_report.artwork_id::TEXT,
        0
    ));

    IF normalized_action IN ('hide', 'dismiss') AND current_report.status <> 'pending_review' THEN
        RAISE EXCEPTION 'REPORT_ACTION_NOT_ALLOWED';
    END IF;
    IF normalized_action = 'reopen' AND current_report.status NOT IN ('actioned', 'dismissed') THEN
        RAISE EXCEPTION 'REPORT_ACTION_NOT_ALLOWED';
    END IF;
    IF normalized_action = 'restore' AND current_report.status <> 'actioned' THEN
        RAISE EXCEPTION 'REPORT_ACTION_NOT_ALLOWED';
    END IF;

    IF normalized_action = 'hide' THEN
        PERFORM public.set_artwork_moderation_visibility(
            current_report.chain_id,
            current_report.artwork_id,
            TRUE,
            normalized_reason,
            normalized_actor
        );
        next_status := 'actioned';
        event_name := 'REPORT_HIDDEN';
        reporter_notification := 'REPORT_ACTIONED';
        creator_notification := 'ARTWORK_HIDDEN';
    ELSIF normalized_action = 'dismiss' THEN
        next_status := 'dismissed';
        event_name := 'REPORT_DISMISSED';
        reporter_notification := 'REPORT_DISMISSED';
    ELSIF normalized_action = 'reopen' THEN
        next_status := 'pending_review';
        event_name := 'REPORT_REOPENED';
        reporter_notification := 'REPORT_REOPENED';
    ELSE
        next_status := 'dismissed';
        event_name := 'REPORT_RESOLVED';
        reporter_notification := 'REPORT_DISMISSED';

        SELECT COUNT(*)
        INTO other_actioned_reports
        FROM public.artwork_reports AS other_report
        WHERE other_report.chain_id = current_report.chain_id
          AND other_report.artwork_id = current_report.artwork_id
          AND other_report.id <> current_report.id
          AND other_report.status = 'actioned';

        IF other_actioned_reports = 0 THEN
            event_name := 'REPORT_RESTORED';
            PERFORM public.set_artwork_moderation_visibility(
                current_report.chain_id,
                current_report.artwork_id,
                FALSE,
                NULL,
                normalized_actor
            );
            creator_notification := 'ARTWORK_RESTORED';
        END IF;
    END IF;

    UPDATE public.artwork_reports
    SET status = next_status,
        reviewed_by = normalized_actor,
        reviewed_at = NOW(),
        decision_reason = normalized_reason,
        updated_at = clock_timestamp()
    WHERE id = current_report.id
    RETURNING updated_at INTO new_updated_at;

    INSERT INTO public.artwork_report_events (
        report_id,
        event_type,
        actor_wallet,
        reason
    ) VALUES (
        current_report.id,
        event_name,
        normalized_actor,
        normalized_reason
    );

    INSERT INTO public.artwork_report_notifications (
        report_id,
        recipient_wallet,
        notification_type
    ) VALUES (
        current_report.id,
        current_report.reporter_wallet,
        reporter_notification
    );

    INSERT INTO public.artwork_report_events (
        report_id,
        event_type,
        actor_wallet,
        reason
    ) VALUES (
        current_report.id,
        'NOTIFICATION_QUEUED',
        normalized_actor,
        NULL
    );

    IF creator_notification IS NOT NULL THEN
        SELECT LOWER(artwork.creator)
        INTO creator_wallet
        FROM public.v41_artworks AS artwork
        WHERE artwork.chain_id = current_report.chain_id
          AND artwork.artwork_id = current_report.artwork_id
        LIMIT 1;

        IF creator_wallet ~ '^0x[0-9a-f]{40}$'
           AND creator_wallet <> current_report.reporter_wallet THEN
            INSERT INTO public.artwork_report_notifications (
                report_id,
                recipient_wallet,
                notification_type
            ) VALUES (
                current_report.id,
                creator_wallet,
                creator_notification
            );
        END IF;
    END IF;

    SELECT COALESCE((
        SELECT visibility.hidden
        FROM public.artwork_moderation_visibility AS visibility
        WHERE visibility.chain_id = current_report.chain_id
          AND visibility.artwork_id = current_report.artwork_id
    ), FALSE)
    INTO artwork_still_hidden;

    RETURN QUERY SELECT current_report.id, next_status, new_updated_at, artwork_still_hidden;
END;
$$;

REVOKE ALL ON FUNCTION public.review_artwork_report(UUID, TIMESTAMPTZ, TEXT, TEXT, TEXT)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.review_artwork_report(UUID, TIMESTAMPTZ, TEXT, TEXT, TEXT)
    TO service_role;
