-- Persistent off-chain artwork moderation state.
-- These tables are intentionally separate from V4.1 indexer projections so
-- projection rebuilds and re-syncs cannot change moderation decisions.

CREATE TABLE IF NOT EXISTS public.artsoul_staff_roles (
    wallet_address TEXT PRIMARY KEY,
    role TEXT NOT NULL CHECK (role IN ('admin', 'moderator', 'team')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    granted_by TEXT,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (wallet_address = LOWER(wallet_address)),
    CHECK (wallet_address ~ '^0x[0-9a-f]{40}$')
);

CREATE TABLE IF NOT EXISTS public.artwork_moderation_visibility (
    chain_id NUMERIC(78, 0) NOT NULL,
    artwork_id NUMERIC(78, 0) NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    hidden_reason TEXT,
    hidden_by TEXT,
    hidden_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (chain_id, artwork_id),
    CHECK (hidden_by IS NULL OR hidden_by ~ '^0x[0-9a-f]{40}$')
);

CREATE INDEX IF NOT EXISTS idx_artwork_moderation_visibility_hidden
    ON public.artwork_moderation_visibility (hidden, updated_at DESC)
    WHERE hidden = TRUE;

CREATE TABLE IF NOT EXISTS public.artwork_moderation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id NUMERIC(78, 0) NOT NULL,
    artwork_id NUMERIC(78, 0) NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('HIDE', 'UNHIDE')),
    reason TEXT,
    actor_wallet TEXT NOT NULL CHECK (actor_wallet ~ '^0x[0-9a-f]{40}$'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_artwork_moderation_log_artwork
    ON public.artwork_moderation_log (chain_id, artwork_id, created_at DESC);

ALTER TABLE public.artsoul_staff_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_moderation_visibility ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artwork_moderation_log ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.artsoul_staff_roles FROM anon, authenticated;
REVOKE ALL ON public.artwork_moderation_visibility FROM anon, authenticated;
REVOKE ALL ON public.artwork_moderation_log FROM anon, authenticated;

GRANT ALL ON public.artsoul_staff_roles TO service_role;
GRANT ALL ON public.artwork_moderation_visibility TO service_role;
GRANT ALL ON public.artwork_moderation_log TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.artwork_moderation_log_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.set_artwork_moderation_visibility(
    p_chain_id NUMERIC,
    p_artwork_id NUMERIC,
    p_hidden BOOLEAN,
    p_reason TEXT,
    p_actor_wallet TEXT
)
RETURNS SETOF public.artwork_moderation_visibility
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF p_actor_wallet IS NULL OR p_actor_wallet !~ '^0x[0-9a-f]{40}$' THEN
        RAISE EXCEPTION 'Invalid moderation actor wallet';
    END IF;

    IF p_hidden AND (p_reason IS NULL OR LENGTH(TRIM(p_reason)) = 0) THEN
        RAISE EXCEPTION 'A reason is required to hide artwork';
    END IF;

    INSERT INTO public.artwork_moderation_visibility (
        chain_id,
        artwork_id,
        hidden,
        hidden_reason,
        hidden_by,
        hidden_at,
        updated_at
    ) VALUES (
        p_chain_id,
        p_artwork_id,
        p_hidden,
        CASE WHEN p_hidden THEN LEFT(TRIM(p_reason), 500) ELSE NULL END,
        CASE WHEN p_hidden THEN p_actor_wallet ELSE NULL END,
        CASE WHEN p_hidden THEN NOW() ELSE NULL END,
        NOW()
    )
    ON CONFLICT (chain_id, artwork_id) DO UPDATE SET
        hidden = EXCLUDED.hidden,
        hidden_reason = EXCLUDED.hidden_reason,
        hidden_by = EXCLUDED.hidden_by,
        hidden_at = EXCLUDED.hidden_at,
        updated_at = EXCLUDED.updated_at;

    INSERT INTO public.artwork_moderation_log (
        chain_id,
        artwork_id,
        action,
        reason,
        actor_wallet
    ) VALUES (
        p_chain_id,
        p_artwork_id,
        CASE WHEN p_hidden THEN 'HIDE' ELSE 'UNHIDE' END,
        CASE WHEN p_hidden THEN LEFT(TRIM(p_reason), 500) ELSE NULL END,
        p_actor_wallet
    );

    RETURN QUERY
    SELECT visibility.*
    FROM public.artwork_moderation_visibility AS visibility
    WHERE visibility.chain_id = p_chain_id
      AND visibility.artwork_id = p_artwork_id;
END;
$$;

REVOKE ALL ON FUNCTION public.set_artwork_moderation_visibility(NUMERIC, NUMERIC, BOOLEAN, TEXT, TEXT)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_artwork_moderation_visibility(NUMERIC, NUMERIC, BOOLEAN, TEXT, TEXT)
    TO service_role;
