export const ARTWORK_STATES = {
    DRAFT: 'DRAFT',
    AUCTION: 'AUCTION',
    SETTLEMENT_PENDING: 'SETTLEMENT_PENDING',
    SETTLEMENT_DEFAULTED: 'SETTLEMENT_DEFAULTED',
    FOR_SALE: 'FOR_SALE',
    SOLD: 'SOLD'
};

export const AUCTION_CONSTANTS = {
    DURATION_MS: 24 * 3600 * 1000,
    EXTENSION_MS: 10 * 60 * 1000,
    EXTENSION_THRESHOLD_MS: 10 * 60 * 1000,
    SETTLEMENT_WINDOW_MS: 24 * 3600 * 1000
};

export const RATE_LIMITS = {
    BIDS_PER_WALLET_PER_HOUR: 10,
    BIDS_PER_WALLET_PER_AUCTION_PER_10MIN: 3,
    OFFERS_PER_WALLET_PER_ARTWORK_PER_HOUR: 1
};

export const RISK_THRESHOLDS = {
    HIGH_RISK_SCORE: 70,
    SPAM_BID_COUNT: 50,
    LOW_PURCHASE_RATE: 0.1
};
